#!/usr/bin/env python3
"""
convert_image.py — Convert any image into the raw format the
Waveshare 3.7" 4-color e-paper (EPD_3IN7G) expects.

Panel: 240 (W) x 416 (H), 4 colors, 2 bits/pixel, 4 pixels packed per byte.
Color codes (must match EPD_3in7g.h):
    0 = Black
    1 = White
    2 = Yellow
    3 = Red

Usage:
    python3 convert_image.py input.jpg output_name

Produces:
    output_name.bin   -> raw packed bytes (for HTTP hosting later)
    output_name.h     -> C array (for embedding directly in firmware now)
"""

import sys
from PIL import Image

PANEL_WIDTH = 240
PANEL_HEIGHT = 416

# The 4 physical colors this panel can show, in the exact index order
# the display driver uses (0=Black, 1=White, 2=Yellow, 3=Red).
PALETTE_RGB = [
    (0, 0, 0),        # 0 Black
    (255, 255, 255),  # 1 White
    (255, 210, 0),    # 2 Yellow
    (200, 30, 30),    # 3 Red
]


def build_palette_image():
    """PIL quantize() needs the palette as a P-mode image."""
    pal_img = Image.new("P", (1, 1))
    flat = []
    for rgb in PALETTE_RGB:
        flat.extend(rgb)
    # Pad to 256 colors (required by PIL palette format)
    flat.extend([0, 0, 0] * (256 - len(PALETTE_RGB)))
    pal_img.putpalette(flat)
    return pal_img


def load_and_fit(path):
    img = Image.open(path).convert("RGB")

    # Fit/crop to the panel's aspect ratio (240x416, portrait) without
    # squashing the image, then resize to exact panel resolution.
    target_ratio = PANEL_WIDTH / PANEL_HEIGHT
    src_ratio = img.width / img.height

    if src_ratio > target_ratio:
        # source is too wide -> crop left/right
        new_width = int(img.height * target_ratio)
        offset = (img.width - new_width) // 2
        img = img.crop((offset, 0, offset + new_width, img.height))
    else:
        # source is too tall -> crop top/bottom
        new_height = int(img.width / target_ratio)
        offset = (img.height - new_height) // 2
        img = img.crop((0, offset, img.width, offset + new_height))

    img = img.resize((PANEL_WIDTH, PANEL_HEIGHT), Image.LANCZOS)
    return img


def quantize_to_panel_colors(img):
    pal_img = build_palette_image()
    # Floyd-Steinberg dithering gives much better perceived detail
    # on a 4-color panel than flat quantization.
    quantized = img.quantize(palette=pal_img, dither=Image.FLOYDSTEINBERG)
    return quantized  # pixel values are now 0/1/2/3 directly


def pack_2bpp(quantized_img):
    """Pack 4 pixels (2 bits each) per output byte, row by row —
    matching exactly what EPD_3IN7G_Display() reads."""
    width, height = quantized_img.size
    bytes_per_row = (width + 3) // 4  # ceil(width/4)
    out = bytearray(bytes_per_row * height)

    pixels = quantized_img.load()
    for y in range(height):
        for x in range(width):
            color = pixels[x, y] & 0x03  # 2-bit color index (0-3)
            byte_index = y * bytes_per_row + (x // 4)
            shift = 6 - 2 * (x % 4)  # pixel 0 = bits 7:6, pixel 3 = bits 1:0
            out[byte_index] |= (color << shift)
    return bytes(out)


def write_c_header(packed_bytes, out_path, array_name):
    with open(out_path, "w") as f:
        f.write(f"// Auto-generated by convert_image.py — {len(packed_bytes)} bytes\n")
        f.write(f"#ifndef {array_name.upper()}_H\n#define {array_name.upper()}_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"const uint8_t {array_name}[{len(packed_bytes)}] = {{\n")
        for i in range(0, len(packed_bytes), 16):
            chunk = packed_bytes[i:i + 16]
            line = ", ".join(f"0x{b:02X}" for b in chunk)
            f.write(f"    {line},\n")
        f.write("};\n\n#endif\n")


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 convert_image.py <input_image> <output_name>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_name = sys.argv[2]

    img = load_and_fit(input_path)
    quantized = quantize_to_panel_colors(img)

    # Save a PNG preview so you can see exactly what the panel will show
    preview_rgb = quantized.convert("RGB")
    preview_rgb.save(f"{output_name}_preview.png")

    packed = pack_2bpp(quantized)

    with open(f"{output_name}.bin", "wb") as f:
        f.write(packed)

    write_c_header(packed, f"{output_name}.h", array_name=f"{output_name}_data")

    print(f"Done. {len(packed)} bytes packed.")
    print(f"  Preview: {output_name}_preview.png  (open this to check colors before flashing)")
    print(f"  Raw:     {output_name}.bin")
    print(f"  Header:  {output_name}.h")


if __name__ == "__main__":
    main()
